# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b75f557f55297879227b3e690000099f0240b77b287d9cb942ebb76fc2dcbf5a2c7bd5be147a345a2e58ec44a7b876518c0c21756b428ba8f3572718f8ac267a

test:
  secret_key_base: 9f6779e9948e56b3bf719a566cfdb47c7b22449e8223ba493283549e2e31ea286cfc266326366217ab95bd7d6f998001b9cf4e6ba66d9526b91724e0bf4096aa

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
